### ISSUE TITLE
make tag / untag messages more informative

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/koji-fedoramessaging-messages#6]
currently the tag / untag summaries are the following:

`rust-difftastic-0.45.0-2.fc38 was untagged from f38-signing-pending`
`rust-difftastic-0.45.0-2.fc38 was tagged into f38-signing-pending`

this summary is generated from the format:

`f"{self.name}-{self.version}-{self.release} was untagged from {self.tag}"`
`f"{self.name}-{self.version}-{self.release} was tagged into {self.tag}"`

from the details in the body below:

```
{
  "body": {
    "build_id": 2165923,
    "instance": "primary",
    "name": "rust-difftastic",
    "owner": "salimma",
    "release": "2.fc38",
    "tag": "f38-signing-pending",
    "tag_id": 56371,
    "user": "autopen",
    "version": "0.45.0"
  },
  "headers": {
    "fedora_messaging_rpm_rust-difftastic": true,
    "fedora_messaging_schema": "koji_fedoramessaging.tag.UntagV1",
    "fedora_messaging_severity": 20,
    "fedora_messaging_user_autopen": true,
    "fedora_messaging_user_salimma": true,
    "sent-at": "2023-03-06T22:35:46+00:00"
  },
  "id": "c0febcd8-b96e-4626-b511-85042400817a",
  "queue": null,
  "topic": "org.fedoraproject.prod.buildsys.untag"
}
```
https://apps.fedoraproject.org/datagrepper/v2/id?id=cd62ee89-504f-4edb-87df-1fc59e57a830&is_raw=true&size=extra-large

@nirik reported in https://github.com/fedora-infra/fmn/issues/769 that this is not detailed enough, and we really need the name of the tagger in there too.

**Comment by ryanlerch** [comment]
@nirik from what i can gather from the body of the message, the `owner`  is the owner of the build, and the `user` is the tagger/untagger ?

so something like:

`rust-difftastic-0.45.0-2.fc38 was untagged from f38-signing-pending by autopen`
`rust-difftastic-0.45.0-2.fc38 was tagged into f38-signing-pending by autopen`

which is the format:

`f"{self.name}-{self.version}-{self.release} was untagged from {self.tag}" by {self.user}`
`f"{self.name}-{self.version}-{self.release} was tagged into {self.tag} by {self.user}"`

My final question though is do we want to include (i.e. do we care about) including the owner field in the summary text?

**Comment by nirik** [comment]
Yeah, not sure. Thats a ton of noise for people, but some owners might care?
