### ISSUE TITLE
"Build finished" events should not be considered as initiated by the build owner

### ISSUE THREAD

**Issue by abompard** [fedora-infra/koji-fedoramessaging-messages#62]
On a build finished event, we should set the `agent_name` to `None` and the `usernames` list to the build owner's username.
This way, the notifications will be sent even when "Include actions I initated" is unticked. It's also more right: the end of the build hasn't been caused by the build owner, but by Koji itself.

**Comment by voxik** [comment]
For more context:

https://pagure.io/fedora-infrastructure/issue/11687#comment-889790
